import { FieldDef } from './edit-dialog'

export const FIELD_DEFS: Record<string, FieldDef[]> = {
  profile: [
    { key: 'name', label: 'Name', type: 'text', required: true },
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'tagline', label: 'Tagline', type: 'text', full: true },
    { key: 'about', label: 'About', type: 'textarea', full: true },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'avatarUrl', label: 'Avatar', type: 'image' },
    { key: 'resumeUrl', label: 'Resume URL', type: 'text' },
    { key: 'available', label: 'Available for hire', type: 'checkbox' },
  ],
  skill: [
    { key: 'category', label: 'Category', type: 'text', placeholder: 'Languages, Web, Tools...' },
    { key: 'name', label: 'Skill name', type: 'text', required: true },
    { key: 'level', label: 'Proficiency (0-100)', type: 'number' },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  education: [
    { key: 'institution', label: 'Institution', type: 'text', required: true, full: true },
    { key: 'degree', label: 'Degree', type: 'text', required: true },
    { key: 'field', label: 'Field', type: 'text' },
    { key: 'period', label: 'Period', type: 'text', placeholder: '2021 — 2025' },
    { key: 'gpa', label: 'GPA / Score', type: 'text' },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
    { key: 'courses', label: 'Relevant courses', type: 'tags', full: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  hackathon: [
    { key: 'title', label: 'Hackathon name', type: 'text', required: true, full: true },
    { key: 'organizer', label: 'Organizer', type: 'text' },
    { key: 'date', label: 'Date', type: 'text', placeholder: 'March 2024' },
    { key: 'result', label: 'Result', type: 'text', placeholder: '1st Place, Top 5...' },
    { key: 'teamSize', label: 'Team size', type: 'number' },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
    { key: 'imageUrl', label: 'Cover image', type: 'image', full: true },
    { key: 'projectUrl', label: 'Project URL', type: 'text' },
    { key: 'tags', label: 'Tech tags', type: 'tags', full: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  contest: [
    { key: 'name', label: 'Contest name', type: 'text', required: true, full: true },
    { key: 'platform', label: 'Platform', type: 'text', placeholder: 'Codeforces, ICPC, CodeChef...' },
    { key: 'date', label: 'Date', type: 'text' },
    { key: 'rank', label: 'Rank / Position', type: 'text' },
    { key: 'rating', label: 'Rating', type: 'text' },
    { key: 'badge', label: 'Badge emoji', type: 'text', placeholder: '🥇 🥈 🥉 ⭐' },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  certificate: [
    { key: 'title', label: 'Certificate title', type: 'text', required: true, full: true },
    { key: 'issuer', label: 'Issuer', type: 'text', required: true },
    { key: 'date', label: 'Date', type: 'text' },
    { key: 'credentialId', label: 'Credential ID', type: 'text' },
    { key: 'credentialUrl', label: 'Credential URL', type: 'text', full: true },
    { key: 'imageUrl', label: 'Certificate image', type: 'image', full: true },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  achievement: [
    { key: 'icon', label: 'Icon (emoji)', type: 'text', placeholder: '🏆 ⭐ 💻' },
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  project: [
    { key: 'title', label: 'Project title', type: 'text', required: true, full: true },
    { key: 'description', label: 'Short description', type: 'textarea', full: true },
    { key: 'longDescription', label: 'Long description', type: 'textarea', full: true },
    { key: 'imageUrl', label: 'Cover image', type: 'image', full: true },
    { key: 'githubUrl', label: 'GitHub URL', type: 'text', full: true },
    { key: 'liveUrl', label: 'Live URL', type: 'text', full: true },
    { key: 'tags', label: 'Tech tags', type: 'tags', full: true },
    { key: 'featured', label: 'Featured project', type: 'checkbox' },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  socialLink: [
    { key: 'platform', label: 'Platform', type: 'text', placeholder: 'GitHub, LinkedIn, Codeforces...' },
    { key: 'url', label: 'URL', type: 'text', required: true, full: true },
    { key: 'icon', label: 'Icon key', type: 'text', placeholder: 'github, linkedin, codeforces...' },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  testimonial: [
    { key: 'name', label: 'Person name', type: 'text', required: true },
    { key: 'role', label: 'Role / Title', type: 'text', required: true, full: true },
    { key: 'company', label: 'Company / Org', type: 'text' },
    { key: 'avatarUrl', label: 'Avatar (optional)', type: 'image' },
    { key: 'rating', label: 'Rating (1-5)', type: 'number' },
    { key: 'quote', label: 'Quote', type: 'textarea', full: true, required: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  currentlyItem: [
    { key: 'type', label: 'Type', type: 'text', placeholder: 'learning, reading, building, listening' },
    { key: 'label', label: 'Label', type: 'text', required: true, full: true },
    { key: 'order', label: 'Order', type: 'number' },
  ],
  faq: [
    { key: 'question', label: 'Question', type: 'text', required: true, full: true },
    { key: 'answer', label: 'Answer', type: 'textarea', full: true, required: true },
    { key: 'category', label: 'Category', type: 'text', placeholder: 'General, Technical, Opportunities...' },
    { key: 'order', label: 'Order', type: 'number' },
  ],
}

export const ENTITY_LABELS: Record<string, string> = {
  profile: 'Profile',
  skill: 'Skill',
  education: 'Education',
  hackathon: 'Hackathon',
  contest: 'Contest',
  certificate: 'Certificate',
  achievement: 'Achievement',
  project: 'Project',
  socialLink: 'Social Link',
  testimonial: 'Testimonial',
  currentlyItem: 'Currently Item',
  faq: 'FAQ',
}
